version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: biochain_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: biochain_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
